---
services:
  frontend:
    image: pashadeviprasanna943/dockerwebapp-app-image
    container_name: my-app
    ports:
      - "3000:8080"
    networks:
      - newnetwork
    depends_on:
      - devopsdb
    deploy:
      replicas: 1

  devopsdb:
    image: pashadeviprasanna943/dockerwebapp-db-image
    container_name: devopsdb
    ports:
      - "3306:3306"
    networks:
      - newnetwork
    volumes:
      - dbvolume:/var/lib/mysql/
    deploy:
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: devopspassword

networks:
  newnetwork:
    driver: bridge

volumes:
  dbvolume:

...
